#MySQL DB Setting
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/super_position
    username: root
    password: #비밀번호
  #devtools
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

#Swagger
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# Mapper Xml Location
mybatis:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true

## SSL Setting
#server:
#  ssl:
#    enabled: true
#    key-store: /etc/letsencrypt/live/api.spp-art.com/keystore.p12
#    key-store-password: #비밀번호
#    key-store-type: PKCS12
#    key-alias: superposition
#  port: 443

cors:
  pathPattern: /**
  allowedOrigins: https://www.spp-art.com