INSERT INTO exhibition (title, subHeading, location, start_date, end_date, status, poster)
VALUES ('Christmas Tree and Neapolitan Baroque Crèche',
        'The Met continues a longstanding holiday tradition with the presentation of its Christmas tree.', 'MET',
        '2023-11-21', '2024-01-07', 'end', 'tree.jpg'),
       ('Proof: Maxime Du Camp’s Photographs of the Eastern Mediterranean and North Africa',
        'Officially encouraged to exploit photography’s “uncontestable exactitude,', 'MET', '2023-10-23', '2024-01-21',
        'end', 'Mediterranean.jpg'),
       ('Vertigo of Color: Matisse, Derain, and the Origins of Fauvism',
        'The exhibition is made possible by The Florence Gould Foundation.', 'MET', '2023-10-13', '2024-01-21', 'end',
        'Fauvism.jpg'),
       ('Picasso: A Cubist Commission in Brooklyn',
        'In 1910 Pablo Picasso (1881–1973) embarked on a decorative commission for the Brooklyn residence of artist',
        'MET', '2023-09-14', '2024-01-14', 'end', 'Picasso.jpg'),
       ('Art for the Millions: American Culture and Politics in the 1930s',
        'The 1930s was a decade of political and social upheaval in the United States,', 'MET',
        '2023-09-07', '2023-12-10', 'end', '1930s.jpg'),
       ('Van Gogh’s Cypresses', 'Van Gogh’s Cypresses is the first exhibition to focus on the trees', 'MET',
        '2023-05-22', '2023-08-27', 'end', 'cypresses.jpg'),
       ('Lineages: Korean Art at The Met', 'METXSuperposition 겨울 전시', 'MET', '2023-12-16', '2023-12-25', 'current',
        'Lineages.jpg'),
       ('The Facade Commission: Nairy Baghramian, Scratching the Back', 'For The Met Fifth Avenue’s facade niches,',
        'MET', '2023-12-16', '2024-05-28', 'current', 'commission.jpg'),
       ('Grounded in Clay: The Spirit of Pueblo Pottery', 'Pueblo Indian pottery embodies four main natural elements',
        'MET', '2023-12-16', '2024-06-04', 'current', 'Pottery.jpg'),
       ('여기는 따뜻해', '성수지앵XSuperposition 겨울 전시', '성수지앵', '2023-12-16', '2023-12-25', 'current', 'dsafsdafsdfaroghg.jpg');

INSERT INTO exhibition (title, subHeading, location, start_date, end_date, status, poster)
VALUES ('여기는 따뜻해', '성수지앵XSuperposition 겨울 전시', '성수지앵', '2023-12-16', '2023-12-25', 'current', 'dsafsdafsdfaroghg.jpg'),
       ('여기는 따뜻해', '성수지앵XSuperposition 겨울 전시', '성수지앵', '2023-12-16', '2023-12-25', 'current', 'dsafsdafsdfaroghg.jpg'),
       ('여기는 따뜻해', '성수지앵XSuperposition 겨울 전시', '성수지앵', '2023-12-16', '2023-12-25', 'current', 'dsafsdafsdfaroghg.jpg'),
       ('Africa & Byzantium',
        'The exhibition is made possible by the Ford Foundation, The Giorgi Family Foundation, and Mary Jaharis.',
        'MET', '2023-12-16', '2024-03-03', 'current', 'africa.jpg'),
       ('Women Dressing Women', 'The exhibition and catalogue are made possible by Morgan Stanley.', 'MET',
        '2023-12-16', '2024-03-03', 'current', 'women.jpg');
